export const typography = {
  title: 24,
  titleSm: 22,
  section: 18,
  sectionSm: 16,
  body: 16,
  bodySm: 14,
  metadata: 13,
  metadataSm: 12,
  caption: 11,
  captionSm: 10,
  weightBold: "700" as const,
  weightSemibold: "600" as const,
  weightMedium: "500" as const,
  weightRegular: "400" as const,
  lineHeightTight: 1.2,
  lineHeightNormal: 1.4,
  lineHeightRelaxed: 1.5,
} as const;
